name: pre-commit

on:
  push:
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**
      - GEOPY-359

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    env:
      SKIP: pylint # pylint will run in another dedicated job (needs poetry)
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python version
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: set PY_HASH
      run: echo "PY_HASH=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> $GITHUB_ENV
    - name: Cache pre-commit tools
      uses: actions/cache@v2
      with:
        path: ~/.cache/pre-commit
        key: precommit-${{ env.PY_HASH }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          precommit-${{ env.PY_HASH }}-
          precommit-
    - name: Run pre-commit hooks on all files
      run: pre-commit run --all-files
